#!/bin/bash
set -o nounset
set -o errexit
set -o errtrace
set -o pipefail

for SRC_DIR in /backup/*/; do
  CLEAN_SRC_DIR=$(basename "$SRC_DIR")
  DEST_DIR=${REMOTE_DIR}/${CLEAN_SRC_DIR}

  echo  "========================= Removing old backup sets for ${HOSTNAME}${SRC_DIR} ========================="
  duplicity ${REMOVE_SET_OPTS} ${COMMON_OPTS} ${DEST_DIR}
done
