#!/bin/bash
set -o nounset
set -o errexit
set -o errtrace
set -o pipefail

if [[ "${#}" -lt 3 ]]; then
  echo "3 arguments are needed:"
  echo "1: File to restore: relative to dir, e.g. hosts"
  echo "2: Remote dir, e.g. etc"
  echo "3: Restore destination, NOTE: must be a rw path that is mounted in docker container, e.g. /restore/
  echo "4: (Optional) time argument for duplicity, e.g. 3D"
  exit 1
fi

FILE=${1:-}
DIR=${2:-}
RESTORE_DEST=${3:-}
TIME=${4:-}

ARGS=""
if [[ -n ${TIME} ]]; then
  ARGS="--time ${TIME}"
fi

duplicity ${ARGS} ${COMMON_OPTS} --file-to-restore "${FILE}" "${REMOTE_DIR}/${DIR}" "${RESTORE_DEST}"
