#!/bin/bash
set -o nounset
set -o errexit
set -o errtrace
set -o pipefail

if [[ "${#}" -eq 0 ]]; then
  echo "Missing argument:"
  echo "Remote dir, e.g. etc"
  exit 1
fi

DIR=${1:-}

duplicity verify $COMMON_OPTS "${REMOTE_DIR}/${DIR}" "/${DIR}"
